site_name: remove-folder and copy-folder scripts
site_url: https://josh-wong.github.io/remove-copy-folder-scripts/

# adds repo details in the top right-hand corner; removing since it's 
# to have in a multidocs site
repo_name: josh-wong/remove-copy-folder-scripts
repo_url: https://github.com/josh-wong/remove-copy-folder-scripts
# warning: this edit page button does not work; I have prioritized the 
# multidocs site, so the edit page button on https://josh-wong.github.io 
# is correct; there doesn't seem to be a way to remove it from one site 
# and keep it on the other.
edit_uri: blob/main/

plugins:
  - search
  - techdocs-core
  # Shows the last updated date
  - git-revision-date

markdown_extensions:
  # Add styles for buttons
  - attr_list
  # Add emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  name: material
  favicon: assets/images/favicon.png
  # logo: assets/images/mkdocs_zune_logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
      primary: blue
      accent: blue
  features:
    # Add custom search functions
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.top

nav:
  - Overview: 'index.md'
  - Getting started: '01_getting-started.md'
  - Configuring the scripts: '02_configuring_scripts.md'
#  - Configuring Task Scheduler: '03_configuring_task_scheduler.md'
#  - Conclusion: '04_conclusion.md'
  - References: '05_references.md'
  - Contributions: '06_contributions.md'
